spring:
  application:
    name: batch
  batch:
    job:
      enabled: false   # run jobs automatically on startup
    jdbc:
      initialize-schema: always

  datasource:
    url: jdbc:postgresql://localhost:5432/batch_app
    driver-class-name: org.postgresql.Driver
    username: tara
    password: yaser

batch-app:
  demoJobCron: 0 10 10 * * *